# Generated by Django 4.1.5 on 2023-01-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('logradouro', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('intensidade', models.CharField(choices=[('LEVE', 'LEVE'), ('MODERADO', 'MODERADO'), ('GRAVE', 'GRAVE')], default='LEVE', max_length=20)),
                ('classificacao', models.CharField(choices=[('LOCALIZADO', 'LOCALIZADO'), ('INTRANSITAVEL', 'INTRANSITAVEL')], default='LOCALIZADO', max_length=20)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alagator.local')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alagator.usuario')),
            ],
        ),
    ]
