# Generated by Django 4.1.5 on 2023-01-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alagator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alagamento',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='alagamento',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
